/**
 * Site photographs.
 *
 *     GET /api/~/erp/blob/<key>  → the image itself, with its content type
 *     PUT /api/~/erp/blob/<key>  → store these bytes under this key
 *
 * WHY THIS EXISTS. Every other piece of the company's data moved to the server;
 * the photographs did not. `ErpStore.putBlob` wrote to IndexedDB in every mode,
 * including the one where the register lives on the server — so a picture taken
 * on the phone was on that phone and nowhere else. The quote line referencing it
 * synced perfectly to the laptop and rendered "(imagen no disponible)", because
 * the state blob held a `storageKey` pointing at bytes that existed on exactly
 * one device. Nothing reported an error; a photograph simply was not there.
 *
 * Bytes on the wire, not base64 in JSON. These are handed straight to an <img>,
 * and base64 would cost a third more storage plus a decode on every read.
 *
 * GET is deliberately cacheable and immutable: keys are generated per upload
 * and never reused for different content, so a browser that has one may keep it
 * forever. That is what makes a page full of thumbnails cheap on the second
 * visit. `private` because these are one company's pictures — no shared cache
 * between operators should ever hold them.
 */
import { blobStore } from "@/lib/erp-runtime";
import { requireUser } from "@/lib/session";
import { tenantFor } from "@/lib/access";
import { guarded, json } from "@/lib/api";
import { FactoryError } from "@repo/kernel";
import { MAX_ATTACHMENT_BYTES, attachmentMime, isAllowedAttachment } from "@/lib/attachments";

export const dynamic = "force-dynamic";

/* The allow-list and the size cap live in `lib/attachments.ts`, not here: this
   module imports the session, the tenant resolver and the blob store, so
   nothing in it can carry a unit test — which is exactly how `application/pdf`
   came to be missing from a list the workspace had always offered PDFs
   against. The list is pinned by a test beside it. */

/** Keys are generated by the page (`img_<base36>_<random>`); anything else is
 *  not something this system created. Bounded and character-restricted so a key
 *  cannot carry a path, a wildcard, or a novel. */
function assertKey(key: string): void {
  if (!/^[A-Za-z0-9_-]{1,128}$/.test(key)) {
    throw new FactoryError("BAD_REQUEST", "Not a valid attachment key.");
  }
}

export async function GET(req: Request, ctx: { params: Promise<{ tenant: string; key: string }> }) {
  const { tenant: param, key } = await ctx.params;
  return guarded(async () => {
    assertKey(key);
    const tenant = await tenantFor(req, param);
    const store = await blobStore(tenant);
    const found = await store.get(key);
    if (!found) throw new FactoryError("NOT_FOUND", "No such attachment.");

    return new Response(Buffer.from(found.bytes), {
      status: 200,
      headers: {
        "content-type": found.mime,
        "content-length": String(found.size),
        "cache-control": "private, max-age=31536000, immutable",
      },
    });
  });
}

export async function PUT(req: Request, ctx: { params: Promise<{ tenant: string; key: string }> }) {
  const { tenant: param, key } = await ctx.params;
  return guarded(async () => {
    assertKey(key);
    const user = await requireUser(req);
    const tenant = await tenantFor(req, param);

    const mime = attachmentMime(req.headers.get("content-type"));
    if (!isAllowedAttachment(mime)) {
      throw new FactoryError(
        "BAD_REQUEST",
        `Attachments must be an image or a PDF, not "${mime}".`,
      );
    }

    const bytes = new Uint8Array(await req.arrayBuffer());
    if (bytes.byteLength === 0) throw new FactoryError("BAD_REQUEST", "Empty attachment.");
    if (bytes.byteLength > MAX_ATTACHMENT_BYTES) {
      throw new FactoryError("BAD_REQUEST", "Attachment is too large (10 MB maximum).");
    }

    const store = await blobStore(tenant);
    await store.put(key, bytes, mime, user);
    return json({ tenant, key, size: bytes.byteLength, mime });
  });
}

export async function DELETE(
  req: Request,
  ctx: { params: Promise<{ tenant: string; key: string }> },
) {
  const { tenant: param, key } = await ctx.params;
  return guarded(async () => {
    assertKey(key);
    await requireUser(req);
    const tenant = await tenantFor(req, param);
    const store = await blobStore(tenant);
    await store.delete(key);
    return json({ tenant, key, deleted: true });
  });
}
