/**
 * THE FOUR EMAIL PAGES IN THE DOCUMENT CATALOGUE, PRINTED FROM THE PRODUCT.
 *
 * `site/documentos/01-cliente/17–20-email-*.html` were hand-written mockups.
 * They were good mockups — the lockup, the summary table, the payment box and
 * the legal foot in them are where the shipped design came from — but they were
 * drawings: nothing rendered them, two of the four described emails the product
 * could not send at all, and the wording in them had not agreed with the
 * message library since the day they were drawn.
 *
 * So they are generated, from the same builder and the same template library
 * the send path uses. A client reviewing the catalogue is then reviewing the
 * product. The one thing added on top is the envelope chrome — From / To /
 * Subject — because the catalogue page has to show WHO the message goes to,
 * which a mail client shows and the message itself does not.
 *
 * Run:  node scripts/email-docs.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "site/documentos/01-cliente");
const Seed = require(path.join(ROOT, "site/erp-seed.js"));
const Eml = require(path.join(ROOT, "site/erp-eml.js"));

const erp = Seed.build("2026-05-05");
erp.ensureCommsTemplates("catalogue");
const events = erp.commsEvents();
const iss = Object.assign(erp._issuerBlock(), {
  privacyUrl: "https://178-105-10-156.sslip.io/privacy.html",
});

/* Which catalogue page is which message. The numbering is the catalogue's, and
   erp-doctypes.js names these files, so the names do not move. */
const PAGES = [
  { file: "17-email-aceptacion.html", key: "quote-accepted", event: "quote-accepted" },
  { file: "18-email-factura.html", key: "invoice-send", event: "invoice-issued" },
  { file: "19-email-recordatorio-pago.html", key: "invoice-reminder", event: "invoice-overdue" },
  { file: "20-email-solicitud-resena.html", key: "warranty-followup", event: "works-finished" },
];

const CSS = `
*,*::before,*::after{box-sizing:border-box}
@page{size:A4;margin:12mm 14mm}
html,body{margin:0;padding:0;background:#EDEDEB}
@media print{
  html,body{background:#fff}
  /* Kerning off, ligatures off. With letter-spacing at zero, kerning is the
     only thing placing one glyph away from the next, and a text extractor
     turns a large enough gap into a space — which is what made "FACTURA"
     extract as "FACT URA" and stop being findable with Ctrl+F. */
  *,*::before,*::after{font-kerning:none;font-variant-ligatures:none;font-feature-settings:"kern" 0,"liga" 0}
  tr,td,table{break-inside:avoid;page-break-inside:avoid}
}
.chrome{background:#F2F2F2;border:1px solid #E0E0E0;border-bottom:0;padding:6mm 8mm;
  font:400 9pt/1.5 Inter,system-ui,-apple-system,"Segoe UI",Arial,sans-serif;color:#3D3D3D;
  max-width:620px;margin:6mm auto 0}
.chrome dl{display:grid;grid-template-columns:auto 1fr;gap:2px 10px;margin:0}
.chrome dt{color:#767676;font-weight:600;text-transform:uppercase;font-size:7pt;padding-top:2px}
.chrome dd{margin:0;color:#000}
`;

const esc = (s) =>
  String(s == null ? "" : s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

let written = 0;
for (const page of PAGES) {
  const tpl = erp.commsTemplate(page.key, "es");
  const ev = events.find((e) => e.event === page.event);
  if (!tpl || !ev) {
    throw new Error(
      `${page.file}: no ${tpl ? "event " + page.event : "template " + page.key} to render it from`,
    );
  }
  const msg = erp.composeCommsMessage(tpl, ev.vars, {
    issuer: iss,
    attachment: tpl.attach ? { name: ev.vars.number + ".pdf", size: "186 kB" } : null,
  });
  const to = tpl.family === "proveedores" ? ev.recipients.supplier : ev.recipients.customer || "";
  const party = erp.state.parties.find((x) => x.email === to);

  /* The message exactly as it is sent, with the cid: marks resolved so a
     browser and a PDF printer can draw them. Nothing else is changed. */
  const built = Eml.withInlineImages(Eml.bodyHtml(msg, iss));
  const inner = built.slice(
    built.indexOf(">", built.indexOf("<body")) + 1,
    built.indexOf("</body>"),
  );

  const html =
    `<!doctype html>\n<html lang="es">\n<head>\n<meta charset="utf-8">\n` +
    `<meta name="viewport" content="width=device-width, initial-scale=1">\n` +
    `<title>${esc(msg.subject)} · CaneiSubirats</title>\n` +
    `<!-- GENERATED by scripts/email-docs.mjs from the message library. Do not\n` +
    `     hand-edit: run the script. The wording lives in erp-engine.js. -->\n` +
    `<style>${CSS}</style>\n</head>\n<body>\n` +
    `<div class="chrome"><dl>\n` +
    `  <dt>De</dt><dd>${esc(iss.tradeName || iss.legalName)} &lt;${esc(iss.email)}&gt;</dd>\n` +
    `  <dt>Para</dt><dd>${esc((party && party.name) || msg.greeting)} &lt;${esc(to)}&gt;</dd>\n` +
    `  <dt>Asunto</dt><dd><b>${esc(msg.subject)}</b></dd>\n` +
    `</dl></div>\n` +
    inner +
    `\n</body>\n</html>\n`;

  fs.writeFileSync(path.join(OUT, page.file), html);
  written += 1;
  console.log(`  ${page.file.padEnd(34)} ${msg.subject}`);
}
console.log(`${written} catalogue email pages regenerated from the message library`);
