/**
 * THE HOUSE MARK, AS THE BYTES AN EMAIL CAN ACTUALLY SHOW.
 *
 * An email cannot fetch a remote image — Gmail and Outlook block it by default
 * and the reader sees a broken box — and it cannot use an inline `<svg>`,
 * because Gmail strips the element outright. The one form that survives both is
 * a PNG attached to the message itself and referenced as `cid:`.
 *
 * So the mark ships as base64 in `site/erp-eml.js`, and this script is what
 * produces it. It is not run at build time and it is not a gate: it is the
 * written-down way to regenerate the constant if the mark ever changes, in the
 * same spirit as scripts/guides-pdf.mjs.
 *
 * The source of truth is the path used by every document in site/documentos —
 * the same 118.391 × 137.002 outline the PDFs draw — rendered at 2× so it stays
 * sharp on a phone.
 *
 * Run:  node scripts/email-logo.mjs          # prints the constant to stdout
 *       node scripts/email-logo.mjs --write  # rewrites it in site/erp-eml.js
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { launchChromium } from "./lib/md-pdf.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/* The mark itself. Kept here rather than read out of a document, because the
   documents carry it inline in twenty places and picking one of them as the
   source would make that document load-bearing for reasons its author never
   agreed to. */
const MARK =
  "M60.449 0 0 38.374V137.002H118.391V38.445ZM107.462 126.073H71.480L56.137 " +
  "122.671V71.986L82.416 65.524H45.953V126.073H10.929V44.382L60.318 13.028L107.462 44.311Z";

/* TWO marks, because a message has two grounds. The masthead is paper, so the
   mark is the house green; the legal foot is the deep green band, where a green
   mark would be a green rectangle. Both are the same outline — a second drawing
   would be a second thing to keep in step. */
const INKS = [
  { name: "MARK_PNG_B64", fill: "#48733C" },
  { name: "MARK_WHITE_PNG_B64", fill: "#FFFFFF" },
];

/* 40 × 46 CSS pixels in the message, at 2× for a retina phone. Transparent
   ground: the mark sits on the white masthead in the mail and on whatever a
   dark-mode client makes of it, and a baked-in white square would be a white
   square in both. */
const W = 80;
const H = 93;

const browser = await launchChromium();
const pg = await browser.newPage({ viewport: { width: W, height: H }, deviceScaleFactor: 1 });
const parts = [];
for (const ink of INKS) {
  await pg.setContent(
    `<!doctype html><html><head><style>html,body{margin:0;padding:0;background:transparent}
     svg{display:block}</style></head><body>
     <svg width="${W}" height="${H}" viewBox="0 0 118.391 137.002" xmlns="http://www.w3.org/2000/svg">
       <path fill="${ink.fill}" fill-rule="nonzero" d="${MARK}"/>
     </svg></body></html>`,
    { waitUntil: "load" },
  );
  const png = await pg.screenshot({ omitBackground: true, type: "png" });
  const b64 = Buffer.from(png).toString("base64");
  parts.push({ ...ink, bytes: png.length, b64 });
}
await browser.close();

const block =
  "  /* Regenerated by scripts/email-logo.mjs — do not hand-edit. */\n" +
  parts
    .map(
      (p) =>
        "  const " +
        p.name +
        " = [\n" +
        p.b64
          .replace(/.{1,96}/g, "$&\n")
          .trimEnd()
          .split("\n")
          .map((l) => '    "' + l + '",')
          .join("\n") +
        '\n  ].join("");\n',
    )
    .join("");

if (!process.argv.includes("--write")) {
  process.stdout.write(block);
  console.error(parts.map((p) => `${p.name}: ${p.bytes} B`).join(" · ") + ` · ${W}×${H}`);
} else {
  const f = path.join(ROOT, "site/erp-eml.js");
  const src = fs.readFileSync(f, "utf8");
  const start = src.indexOf("  /* Regenerated by scripts/email-logo.mjs");
  const endMark = '].join("");\n';
  if (start < 0) throw new Error("the constant block is not in site/erp-eml.js");
  let end = start;
  for (let i = 0; i < parts.length; i += 1) {
    end = src.indexOf(endMark, end);
    if (end < 0) throw new Error("the constant block is shorter than expected");
    end += endMark.length;
  }
  fs.writeFileSync(f, src.slice(0, start) + block + src.slice(end));
  console.log("site/erp-eml.js · marks updated · " + parts.map((p) => p.bytes + " B").join(" + "));
}
