// =============================================================================
// Copies the OCR runtime out of node_modules into site/vendor/, which is
// committed.
//
// WHY COMMITTED. `.github/workflows/pages.yml` publishes `site/**` from a bare
// checkout with no Node and no install step, so anything the browser needs at
// runtime has to already be a file in the repository. And the two things this
// pipeline is for — a bare static host, and capture on a site with no signal —
// both forbid the CDN these libraries reach for by default.
//
// WHY A SCRIPT rather than a one-time copy: so the provenance of ~7 MB of
// binaries is a command anybody can re-run and diff, and so upgrading is
// "bump the version, run this" rather than an archaeology exercise.
//
// Run: node tools/vendor-ocr.mjs
// =============================================================================
import { copyFileSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "site", "vendor");

const pkgDir = (name) => dirname(require.resolve(`${name}/package.json`));
const version = (name) =>
  JSON.parse(readFileSync(join(pkgDir(name), "package.json"), "utf8")).version;

/**
 * What ships, and why each one.
 *
 * The Tesseract core is the SIMD/LSTM build only. Every browser this app
 * supports has had WebAssembly SIMD for years, and carrying the non-SIMD
 * fallback as well would add 2.8 MB to the repository for a runtime nobody
 * here has. `tesseract-core-simd-lstm.js` is named explicitly as `corePath`
 * in erp-ocr.js so the library never probes for the others.
 *
 * The language data is `4.0.0_best_int`, not the standard `4.0.0`: the S0b
 * spike measured no accuracy difference at this document quality and it cuts
 * the two languages from 10.58 MB to 2.61 MB.
 */
const FILES = [
  ["pdfjs-dist", "build/pdf.min.mjs", "pdfjs/pdf.min.mjs"],
  ["pdfjs-dist", "build/pdf.worker.min.mjs", "pdfjs/pdf.worker.min.mjs"],
  ["tesseract.js", "dist/tesseract.min.js", "tesseract/tesseract.min.js"],
  ["tesseract.js", "dist/worker.min.js", "tesseract/worker.min.js"],
  ["tesseract.js-core", "tesseract-core-simd-lstm.js", "tesseract/tesseract-core-simd-lstm.js"],
  ["tesseract.js-core", "tesseract-core-simd-lstm.wasm", "tesseract/tesseract-core-simd-lstm.wasm"],
  ["@tesseract.js-data/spa", "4.0.0_best_int/spa.traineddata.gz", "tessdata/spa.traineddata.gz"],
  ["@tesseract.js-data/cat", "4.0.0_best_int/cat.traineddata.gz", "tessdata/cat.traineddata.gz"],
];

rmSync(OUT, { recursive: true, force: true });

let total = 0;
const manifest = [];
for (const [pkg, from, to] of FILES) {
  const src = join(pkgDir(pkg), from);
  const dest = join(OUT, to);
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(src, dest);
  const bytes = statSync(dest).size;
  total += bytes;
  manifest.push({ file: to, from: `${pkg}@${version(pkg)}/${from}`, bytes });
  console.log(
    `${to.padEnd(46)} ${(bytes / 1024).toFixed(0).padStart(6)} KB  ${pkg}@${version(pkg)}`,
  );
}

writeFileSync(
  join(OUT, "MANIFEST.json"),
  JSON.stringify(
    {
      note: "Generated by tools/vendor-ocr.mjs. Third-party runtime, committed because pages.yml publishes site/** from a bare checkout with no Node. Do not edit by hand.",
      totalBytes: total,
      files: manifest,
    },
    null,
    2,
  ) + "\n",
);

console.log(`\ntotal ${(total / 1024 / 1024).toFixed(2)} MB in site/vendor/`);
