import Foundation

/// Single source of truth for what the app points at.
///
/// The app is a premium native shell around the **live** web app. Because every
/// screen is loaded from the web, anything that changes on the server flows into
/// the app on the next launch or pull-to-refresh — no App Store update required
/// for content or workflow changes.
enum Config {

    /// Base URL of the running ERP.
    ///
    /// This points at the SERVER, which is the only address where the company's
    /// data actually lives. It used to point at GitHub Pages, and that is worth
    /// understanding rather than just correcting: Pages serves a static copy of
    /// the same screens with no database behind them, so the app looked right
    /// and worked — every screen rendered, every form saved — while writing to
    /// storage inside the phone. A customer entered on a laptop was simply not
    /// there on the phone, and nothing reported an error, because from the
    /// app's point of view nothing had gone wrong. A shell around the wrong
    /// address is indistinguishable from a shell around the right one until
    /// somebody tries to share a record.
    ///
    /// The trailing `/workspace/` matters: the server serves the API at the
    /// root and the screens beneath that path.
    ///
    /// Changing this one line moves the whole app. When the real domain
    /// arrives, this is what changes — and only this, because `internalHosts`
    /// below is derived from it rather than repeated.
    static let baseURL = URL(string: "https://178-105-10-156.sslip.io/workspace/")!

    /// Marketing name shown in the splash and About.
    static let appName = "Canei Subirats"
    static let appTagline = "ERP for reformas"

    /// A short marker appended to the WKWebView user-agent so the web app can
    /// detect it is running inside the native shell.
    ///
    /// As of 1.1 the web app actually READS it. Until then nothing did, which
    /// meant a phone inside this app stacked three things at the bottom of the
    /// screen: the web app's own five-icon section bar, this app's floating tab
    /// bar over the top of it, and the web app's site-action button positioned
    /// to clear the bar that was no longer the one in front. Under the marker
    /// the web bar stands down — the native tab bar does that job — and the
    /// breadcrumb becomes the opener for the subsection list, which is the one
    /// thing a six-tab native bar cannot reach.
    ///
    /// The web app matches on `CaneiApp/` and not on the version, so an older
    /// build keeps working against a newer site. Keep the prefix.
    static let userAgentMarker = "CaneiApp/1.1 (iOS; native-shell)"

    /// The tabs of the app, READ FROM `nav.json` — never written here.
    ///
    /// They used to be six hardcoded English strings, and Android had six
    /// hardcoded Spanish ones, and the web had a third set that actually
    /// translated. So the app showed "Sales" over a page whose own breadcrumb
    /// said "Commercial", and would have shown "Sales" on a Spanish phone too.
    /// `i18n.js` runs inside the web view and cannot reach a native tab bar,
    /// and this project has no .strings files, so no amount of translating the
    /// web could ever have fixed the bar above it.
    ///
    /// `nav.json` is generated by scripts/gen-nav-manifest.mjs from SECTIONS in
    /// erp.html — the same list the web nav is built from — with every label
    /// resolved through the same dictionary. Rename a section once and every
    /// surface follows. CI regenerates and diffs it, so the two cannot drift.
    ///
    /// Bundled rather than fetched: the tab bar exists before the first request
    /// completes, and a bar that appears empty for a second is worse than one
    /// that is a build behind. The bundled copy is refreshed on every app build.
    /// The ERP role of the account the web layer last signed in as.
    ///
    /// Written by the web app over the `native` bridge once its session is
    /// resolved, read here at launch. It is deliberately the same arrangement
    /// as `uiLanguage` below, with the same honest limitation: the bar follows
    /// on the NEXT launch, because a tab bar that appears after the first
    /// request completes is worse than one that is a launch behind.
    ///
    /// Nothing here is a permission. The web app sends a site worker back to
    /// the hours screen from every route, and the server refuses every write
    /// this account may not make — so a stale bar is a tidiness problem.
    static var erpRole: String? {
        UserDefaults.standard.string(forKey: "canei_role")
    }

    static let tabs: [WebTab] = NavManifest.load(role: erpRole)

    /// The language the tab bar is drawn in.
    ///
    /// The device's own language, overridden by a choice the operator made in
    /// the app (which the web view mirrors into shared defaults). It is NOT
    /// live: switching language inside the web view relabels the pages
    /// immediately and the bar on the next launch. Making the bar follow
    /// instantly means republishing the tabs from a cookie read, which is a
    /// bigger change than the mismatch justified — noted rather than hidden.
    static var uiLanguage: String {
        if let chosen = UserDefaults.standard.string(forKey: "canei_lang"),
           ["es", "ca", "en"].contains(chosen) {
            return chosen
        }
        let device = Locale.preferredLanguages.first?.prefix(2).lowercased() ?? "es"
        return ["es", "ca", "en"].contains(device) ? device : "es"
    }

    /// Hosts that should open inside
    /// Hosts that should open inside the app's web views. Everything else
    /// (mailto, tel, external websites) is handed to the system.
    ///
    /// DERIVED from `baseURL`, not written out again. When this was a second
    /// hardcoded copy of the host, repointing the app meant editing two lines
    /// that look unrelated — and missing the second one sends every tab to
    /// Safari instead of the web view, which reads as "the app is broken"
    /// rather than "one constant is stale".
    static let internalHosts: Set<String> = Set([baseURL.host].compactMap { $0 })
}
